version: "3.8"
services:
  api:
    build: .
    container_name: sombra-courses-api
    image: sombra-courses-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-tier
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST_DEV=db
  db:
    container_name: postgres
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data/db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER_DEV
      - POSTGRES_PASSWORD=$DB_PASS_DEV
      - POSTGRES_DB=$DB_NAME_DEV
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge

