version: "3"
services:
  api:
    build: .
    container_name: sombra-courses-api
    image: sombra-courses-api:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-tier
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
  db:
    container_name: postgres
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data/db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge

